name: CI

on:
  release:
    types: [created, published]

jobs:
  build_release_macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - run: curl https://sh.rustup.rs -sSf | sh -s -- -y
      - run: $HOME/.cargo/bin/cargo build --release
      - run: target/release/gleam --version
      - id: create_archive
        run: |
          ARCHIVE=gleam-$TAG_NAME-macos.tar.gz
          tar -czvf $ARCHIVE -C target/release gleam 
          echo ::set-output name=ASSET::$ARCHIVE
        env:
          TAG_NAME: ${{ github.event.release.tag_name }}
      - uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ${{ steps.create_archive.outputs.ASSET }}
          asset_name: ${{ steps.create_archive.outputs.ASSET }}
          asset_content_type: application/gzip

  build_release_linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: cargo build --release
      - run: target/release/gleam --version
      - id: create_archive
        run: |
          ARCHIVE=gleam-$TAG_NAME-linux-amd64.tar.gz
          tar -czvf $ARCHIVE -C target/release gleam 
          echo ::set-output name=ASSET::$ARCHIVE
        env:
          TAG_NAME: ${{ github.event.release.tag_name }}
      - uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ${{ steps.create_archive.outputs.ASSET }}
          asset_name: ${{ steps.create_archive.outputs.ASSET }}
          asset_content_type: application/gzip
